#!/bin/bash
# Hook: PostToolUseFailure
# Logs failures to learn-failures.yaml for pattern detection

set -euo pipefail

input=$(cat)
tool_name=$(echo "$input" | jq -r '.tool_name // "unknown"')
error=$(echo "$input" | jq -r '.error // "no error message"')
timestamp=$(date -Iseconds)
session_id="${CLAUDE_SESSION_ID:-unknown}"

FAILURES_FILE=".claude/knowledge/learn-failures.yaml"

# Ensure file exists with header
if [[ ! -f "$FAILURES_FILE" ]] || [[ ! -s "$FAILURES_FILE" ]]; then
  echo "# Failure Log - Auto-generated by failure-logger.sh" > "$FAILURES_FILE"
  echo "# Used by system-wrapup to detect patterns and propose automation" >> "$FAILURES_FILE"
  echo "failures:" >> "$FAILURES_FILE"
fi

# Append failure entry
cat >> "$FAILURES_FILE" << EOF
  - id: "fail-$(date +%s)"
    timestamp: "$timestamp"
    session: "$session_id"
    tool: "$tool_name"
    error: |
      $error
    status: pending
    pattern: null
EOF

# Log to stderr for visibility (won't affect hook output)
echo "[failure-logger] Logged failure: $tool_name" >&2
